export default {
    mblogInfo: '/api/mbloginfo',
    participantRepostFrom: '/api/participantrepostfrom',
    participantRepostVerified: '/api/participantrepostverified',
    participantRepostGender: '/api/participantrepostgender',
    participantRepostAddv: '/api/participantrepostaddv',
    participantRepostTrue: '/api/participantreposttrue',
    participantRepostMeasure: '/api/participantrepostmeasure',
    spreadTimeline: '/api/spreadtimeline',
    spreadRepostRelative: '/api/spreadrepostrelative',
    spreadRepostDeep: '/api/spreadrepostdeep',
    spreadRepostKeyuser: '/api/spreadrepostkeyuser',
    spreadRepostKeyuserRoad: '/api/spreadrepostkeyuserroad',
    spreadRepostBoom: '/api/spreadrepostboom',
    spreadOverview: '/api/spreadoverview',
    repostWordcloud: '/api/repostwordcloud',
}
