export default {
    masterBaseInfo: '/api/masterbaseinfo',
    fanGender: '/api/fangender/',
    fanAddV: '/api/fanaddv',
    aliveFans: '/api/alivefans',
    trueFans: '/api/truefans',
    fanMeasure: '/api/fanmeasure',
    fanVerifiedType: '/api/fanverifiedtype',
    followGender: '/api/followgender',
    followAddV: '/api/followaddv',
    followMeasure: '/api/followmeasure',
    followVerifiedType: '/api/followverifiedtype',
    statusesTimeline: '/api/statusestimeline',
    statusesActiveTime: '/api/statusesactivetime',
    statusesIndex: '/api/statusesindex',
    statusesRetweet: '/api/statusesretweet',
};
