export default {
    masterBaseInfo: '/api/masterbaseinfo',
    fanGender: '/api/fangender/',
    aliveFans: '/api/alivefans',
    followGender: '/api/followgender',
    followRank: '/api/followrank',
    fanRank: '/api/fanrank',
    followFollowCount: '/api/followfollowcount',
    followFollowerCount: '/api/followfollowercount',
    fanFollowCount: '/api/fanfollowcount',
    fanFollowerCount: '/api/fanfollowercount',
    followStatusCount: '/api/followstatuscount',
    fanStatusCount: '/api/fanstatuscount',
    masterStatusesTimeline: '/api/masterstatusestimeline',
    masterStatusesIndex: '/api/masterstatusesindex',
};
